internxt/drive-mobile

src/redux/actions/user.actions.ts, src/screens/Login/index.tsx
Reverts internxt/drive-mobile#37
=> revert "fix/login-button-blocked"

android/app/build.gradle, ios/drivemobile.xcodeproj/project.pbxproj, ios/drivemobile/Info.plist, package.json, src/components/FileItem/index.tsx, src/helpers/toast.ts, src/modals/CreateFolderModal/index.tsx, src/modals/RenameModal/index.tsx, src/modals/ShareFilesModal/index.tsx, src/redux/actions/file.actions.ts, src/redux/actions/user.actions.ts, src/redux/reducers/files.reducer.ts, src/screens/ChangePassword/index.tsx, src/screens/FileExplorer/index.tsx, src/screens/Login/index.tsx, src/screens/StorageWebView/index.tsx, src/screens/TabExplorer/index.tsx, src/screens/TabExplorer/myTabBar.tsx
Fixes:
- Disable long press
- Resize navigation bar
- Notify share link copied
Features:
- Quick delete
=> Add last fixes to version 1.4.1 + quick delete

src/screens/Register/index.tsx
Standardizes signup tracking name.
=> Fix signup tracking name

src/components/modals/AddModal/index.tsx, src/components/modals/CreateFolderModal/index.tsx, src/components/modals/SortModal/index.tsx, src/screens/AuthenticatedNavigator/index.tsx, src/store/slices/ui/index.ts, src/types/ui.ts
This PR refactors the CreateFolderModal component so it can be reused isolated from Redux
=> [_]: Refactor CreateFolderModal component, isolate from Redux

__tests__/unit/services/photos/sync/devicePhotosSyncChecker.spec.ts, __tests__/unit/services/photos/sync/photosSyncManager.spec.ts, app.config.ts, src/navigation/RootNavigator.tsx, src/screens/PhotosGalleryScreen/index.tsx, src/services/photos/PhotosLocalDatabaseService/index.ts, src/services/photos/index.ts, src/services/photos/sync/DevicePhotosSyncChecker.ts, src/store/slices/drive/index.ts, src/store/slices/photos/index.ts
Improves the Photos sorting during the upload introducing the photo in the correct position by time
=> [DRIV-129]: (fix) Improve Photos sorting system during upload

src/services/photos/sync/PhotosSyncManager.ts, src/store/slices/photos/index.ts, src/store/slices/photos/thunks/sync.ts
Includes photos usage in the total displayed usage, now it will be drive usage + photos usage = total usage in kb
=> [_]: Include photos usage in total usage

assets/lang/strings.ts, src/components/modals/PhotosPreviewOptionsModal/index.tsx, src/screens/PhotosPreviewScreen/index.tsx, src/screens/PhotosPreviewScreen/modals.tsx, src/store/slices/ui/index.ts, src/styles/tailwind.css, src/styles/tailwind.json
Updated UI for Photos full size image viewing
=> [DRIV-146]: Update photos full size display UI

babel.config.js, ios/Podfile.lock, package.json, src/App.tsx, src/components/ui-kit/index.ts, src/components/ui-kit/view/ImageViewer/ImageViewer.tsx, src/components/ui-kit/view/ImageViewer/index.ts, src/screens/PhotosPreviewScreen/index.tsx, src/styles/tailwind.css, src/styles/tailwind.json, tsconfig.json, yarn.lock
ImageViewer component implementation, this componentes allows image manipulation via gestures, currently it allows:
- Zooming
- Panning (move the photo around)
- Rotation
=> [DRIV_144]: ImageViewer component, allow rotate, zoom and pan

package.json, src/services/NewsletterService.ts
I hardcoded a hardcoded value, so we don't have the same problem anymore.
Says no one ever.
=> [_]: Use new newsletter group id, prepare for release

package.json, src/components/forms/SignUpForm/index.tsx, src/screens/SignInScreen/index.tsx, src/services/AuthService.ts, src/services/UserService.ts, src/services/common/sdk/SdkManager.ts, src/store/slices/auth/index.ts, yarn.lock
Some methods in the app such login and register was using a raw fetch() to the drive server, this PR refactors those methods to use the internxt-sdk ones instead.
=> [_]:(chore) Move login and register methods to use SDK instead of raw fetch

src/services/photos/constants.ts
Branch coming from feature/deactivate-account-screen.
Enable Photos Analytics
=> [MT-47]: (feature) Enable Photos Analytics

src/components/DriveItemGrid/index.tsx, src/components/DriveList/index.tsx, src/components/modals/BottomModal/index.tsx, src/components/modals/MoveItemsModal/index.tsx, src/components/modals/PlansModal/index.tsx, src/components/ui-kit/index.ts, src/components/ui-kit/view/VirtualizedListView/VirtualizedListView.tsx, src/components/ui-kit/view/VirtualizedListView/index.ts, src/store/slices/drive/index.ts, src/styles/global.ts, src/styles/tailwind.css, src/styles/tailwind.json, src/types/drive.ts
Use RecyclerListView instead of Flatlist for Drive lists, the benefits are:
- Improved memory usage, the items are recycled
- Virtualized by default, only the visible items are rendered
- Improved scroll
- More resources free for other app processes such photos sync
=> [MT-61]:(chore) Use RecyclerListView instead of Flatlist for Drive lists

assets/lang/strings.ts, package.json, src/components/DriveItemTable/index.tsx, src/components/modals/BottomModal/index.tsx, src/components/modals/DriveItemInfoModal/index.tsx, src/components/modals/SharedLinkInfoModal/SharedLinkInfoModal.tsx, src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx, src/components/modals/SharedLinkSettingsModal/animations.ts, src/components/modals/SharedLinkSettingsModal/index.ts, src/hooks/useDriveItem.ts, src/screens/drive/SharedScreen/SharedScreen.tsx, src/services/drive/share/driveShare.service.ts, src/store/slices/drive/index.ts, src/styles/tailwind.css, src/styles/tailwind.json, src/types/drive.ts, src/useCases/drive/getShareLink.ts, yarn.lock
Provide password enable/disable support for Drive share links for folders and files
=> [MT-55]:(feature) Password support for share links

assets/lang/strings.ts, ios/Internxt/Internxt.entitlements, src/components/AppButton/index.tsx, src/components/AppTextInput/index.tsx, src/components/AppVersionWidget/index.tsx, src/components/LoadingSpinner/index.tsx, src/components/forms/SignUpForm/index.tsx, src/navigation/RootNavigator.tsx, src/screens/ForgotPasswordScreen/index.tsx, src/screens/SettingsScreen/index.tsx, src/screens/SignInScreen/index.tsx, src/screens/SignUpScreen/index.tsx, src/services/AppService.ts, src/services/AuthService.ts, src/services/photos/sync/photosSyncManager/photosSyncManager.ts, src/styles/tailwind.css, src/styles/tailwind.json, src/types/ui.ts
New SignIn and SignUp screens, redesigned delete account screen
=> [MT-72]:(feature) New SignIn and SignUp screens

src/helpers/crypt/crypt.spec.ts, src/helpers/crypt/crypt.ts, src/helpers/crypt/index.ts, src/helpers/index.ts
Make stronger filename validations to prevent RCE (Remote Code Execution) attacks
=> [_]:(fix) Stronger filename validation and unit tests

src/helpers/crypt/crypt.spec.ts, src/helpers/crypt/crypt.ts
=> [_]:Allow numbers as filenames

src/components/forms/SignUpForm/index.tsx, src/components/modals/AddModal/index.tsx, src/components/modals/DriveDownloadModal/index.tsx, src/components/modals/SharedLinkInfoModal/SharedLinkInfoModal.tsx, src/screens/DriveScreen/index.tsx, src/screens/SignInScreen/index.tsx, src/screens/common/TrashScreen/TrashScreen.tsx, src/services/AnalyticsService.ts, src/services/AuthService.ts, src/services/PaymentService.ts, src/services/photos/constants.ts, src/store/slices/auth/index.ts, src/store/slices/drive/index.ts, src/useCases/drive/deleteShareLink.ts, src/useCases/drive/getShareLink.ts, src/useCases/drive/trash.ts
⚠️ Merge feature/drive-trash first, this branch is coming from it ⚠️
Added mobile events for auth, item upload, download, delete etc.
Implemented events can be found here: https://inxt.atlassian.net/wiki/spaces/DATA/pages/49905665/Key+Events+All+Platforms
=> [MT-76]:(feature) Mobile events for auth and Drive

src/network/NetworkFacade.ts, src/network/download.ts, src/services/FileSystemService.ts, src/services/common/filesystem/errors.ts, src/services/common/filesystem/fileCacheManager.spec.ts, src/services/common/filesystem/fileCacheManager.ts, src/services/common/filesystem/index.ts, src/services/common/index.ts, src/services/drive/constants.ts, src/services/drive/file/driveFileCache.service.ts, src/services/drive/file/index.ts, src/services/drive/index.ts, src/services/photos/utils/photosUtils.spec.ts, src/store/slices/drive/index.ts
Implemented File cache manager, a system that given a directory maintains only the most recently used files that doesn't exceeds the given configurated limits
=> [MT-86]:(feature) Drive file cache manager

android/app/build.gradle, app.config.ts, assets/lang/strings.ts, ios/Internxt.xcodeproj/project.pbxproj, src/App.tsx, src/components/PhotosSyncStatusWidget/index.tsx, src/components/SettingsGroup/index.tsx, src/contexts/Photos/Photos.context.tsx, src/navigation/TabExplorerNavigator.tsx, src/screens/PhotosPermissionsScreen/index.tsx, src/screens/SettingsScreen/index.tsx, src/services/AsyncStorageService.ts, src/services/AuthService.ts, src/store/slices/auth/index.ts, src/styles/tailwind.css, src/styles/tailwind.json, src/types/index.ts, src/types/navigation.ts
Enable or disable the Photos sync
=> [MT-77]:(feature) Enable/disable Photos sync from settings

app.config.ts, package.json, src/components/AppVersionWidget/index.tsx, src/helpers/headers.ts, src/services/AppService.ts, src/services/common/sdk/SdkManager.ts
- Auto increment Drive Mobile version automatically
- Added Slack preparation for release notification
=> [_]:(feature) Get package version function

src/components/AppToast/index.tsx, src/components/drive/lists/DriveList/DriveList.tsx, src/screens/common/TrashScreen/TrashScreen.tsx, src/services/drive/trash/driveTrash.service.ts, src/useCases/drive/trash.ts
=> [MT-112]: Drive trash pagination

assets/lang/strings.ts, src/App.tsx, src/components/modals/CenterModal/index.tsx, src/components/modals/DriveItemInfoModal/index.tsx, src/services/FileSystemService.ts
Allow to download Drive files on Android, files are stored on `Download/Internxt Downloads` directory
=> [MT-109] Download item to device storage on Android

.gitignore, src/contexts/Photos/Photos.context.tsx, src/services/photos/sync/devicePhotosScanner/devicePhotosScanner.ts, src/services/photos/utils/photosUtils.ts, src/types/photos.ts, src/useCases/photos/saveToGallery.ts
- Fix photos refresh attempting to restart the sync process
=> [MT-105]:(fix) Fix photos refresh while sync is running

src/services/photos/sync/devicePhotosScanner/devicePhotosScanner.ts
- New step when upgrading plan, now it should be confirmed
- UI redesign for the Plan subscription modal
https://gyazo.com/fe86f66300790551eedb2ceb53abb27f
=> [MT-113]:(feature) New plan change confirmation UI

src/services/AnalyticsService.ts, src/store/slices/storage/index.ts
Send Analytics usage event every time we request Photos and Drive usage
=> [MT-118]: Add usage analytics event

android/app/build.gradle, android/build.gradle, package.json, src/components/GalleryItem/index.tsx, src/contexts/Photos/Photos.context.tsx, src/contexts/Photos/sync.ts, src/services/AppService.ts, src/services/ErrorService.ts, src/services/photos/network/PhotosNetworkManager.ts, src/services/photos/sync/photosLocalSyncManager/photosLocalSyncManager.ts, src/store/slices/auth/index.ts, src/store/slices/storage/index.ts, src/types/photos.ts, tsconfig.json, yarn.lock
Now you can sync your photos with the app in background - Only available for Android
=> [PB-106]: Upload Photos using the MobileSDK v1

src/services/ErrorService.ts
Now you can sync your photos with the app in background - Only available for Android
=> 1.5.27 release

__mocks__/@internxt/mobile-sdk.ts, android/app/build.gradle, package.json, src/services/photos/network/PhotosNetworkManager.ts, src/services/photos/sync/photosLocalSyncManager/photosLocalSyncManager.ts, yarn.lock
- Implement a retry mechanism when a background photo processing fails
- Create video thumbnails correctly from a video range, not the entire video
- Added debugging utils to the Mobile SDK
=> [PB-799]: Improve background processing retry on fail, generate video thumbnails correctly

assets/lang/strings.ts, ios/Podfile.lock, src/components/modals/CenterModal/index.tsx, src/components/modals/DriveRenameModal/index.tsx, src/helpers/filetypes.ts, src/screens/drive/DrivePreviewScreen/DrivePreviewScreen.tsx
This PR refactors the rename modal to match the Figma provided design.
Also fixes a bug that prevents the previews for files with uppercase extension to work
=> [PB-559]:(fix) Improve rename modal

src/components/modals/SharedLinkInfoModal/SharedLinkInfoModal.tsx, src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx, src/hooks/useDriveItem.ts, src/screens/HomeScreen/index.tsx, src/screens/drive/SharedScreen/SharedScreen.tsx, src/services/drive/database/driveLocalDB.ts, src/services/drive/folder/driveFolder.service.ts, src/services/drive/share/driveShare.service.ts, src/types/drive.ts, src/useCases/drive/deleteShareLink.ts, src/useCases/drive/filterSharedItems.ts, src/useCases/drive/getShareLink.ts, src/useCases/drive/loadSharedItems.ts
- Removed Shared Links view
- Add new call to create public share links
- Removed Shared Links options
=> [PB-1047] feature/Shared links are not working on mobile

.vscode/settings.json, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, ios/Internxt.xcodeproj/project.pbxproj, ios/Internxt/Info.plist, ios/Internxt/Supporting/Expo.plist, package.json, src/components/modals/AddModal/index.tsx, src/components/modals/CreateFolderModal/index.tsx, src/components/modals/DriveItemInfoModal/index.tsx, src/contexts/Drive/Drive.context.tsx, src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx, src/services/FileSystemService.ts, src/services/drive/database/driveLocalDB.ts, src/services/drive/file/driveFile.service.ts, src/services/drive/folder/driveFolder.service.ts, src/store/slices/auth/index.ts
This PR fixes a bug that was preventing files with accents from being exported in iOS. It also removed unwanted underscores replacing white spaces in filenames when exporting them
=> [PB-1426]:(fix) Fix error when exporting files with accents on iOS

assets/lang/strings.ts, ios/.xcode.env, ios/Internxt.xcodeproj/project.pbxproj, ios/Internxt/Info.plist, ios/Internxt/Supporting/Expo.plist, ios/Podfile.lock, package.json, src/components/BottomModalOption/index.tsx, src/components/GalleryItem/index.tsx, src/components/gallery-views/GalleryAllView.tsx, src/components/modals/PhotosPreviewInfoModal/index.tsx, src/components/modals/PhotosPreviewOptionsModal/index.tsx, src/contexts/Photos/Photos.context.tsx, src/helpers/strings.ts, src/screens/PhotosGalleryScreen/index.ios.tsx, src/screens/PhotosPreviewScreen/index.tsx, src/screens/SettingsScreen/index.tsx, src/services/AuthService.ts, src/services/LanguageService.ts, src/services/common/logger/logger.service.ts, src/services/common/time/time.service.ts, src/services/photos/network/PhotosNetworkManager.ts, src/services/photos/preview/photosPreviewFixer.service.ts, src/services/photos/sync/devicePhotosScanner/devicePhotosScanner.ts, src/services/photos/sync/photosRemoteSyncManager/photosRemoteSyncManager.ts, src/styles/tailwind.css, src/styles/tailwind.json, src/useCases/photos/downloadFullSizePhotosItem.ts, yarn.lock
This PR replaces the JS Photos gallery view and uses https://github.com/Shopify/flash-list instead. 
It also adds a new service to fix the previews for Photos with incorrect aspect ratio.
=> [PB-1602]:(fix) Use FlashList instead of RecyclerListView for Photos gallery

src/components/drive/lists/items/DriveListModeItem/DriveListModeItem.tsx, src/components/modals/DriveItemInfoModal/index.tsx, src/components/modals/MoveItemsModal/index.tsx, src/contexts/Drive/Drive.context.tsx, src/navigation/LinkingConfiguration.ts, src/screens/common/TrashScreen/TrashEmptyState.tsx, src/screens/common/TrashScreen/TrashScreen.tsx, src/screens/common/TrashScreen/TrashScreenHeader.tsx, src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx, src/services/PaymentService.ts, src/services/common/media/image.service.ts, src/services/drive/file/driveFile.service.ts, src/styles/tailwind.css, src/styles/tailwind.json, src/types/drive.ts, src/useCases/drive/trash.ts
- Include folderId for trash correctly
- Restore trash items to the root folder by default
=> [_]: Trash issue when moving files/folders back to the root folder

src/components/SwipeBackHandler/index.tsx, src/screens/drive/DrivePreviewScreen/DrivePreviewScreenHeader.tsx
- Added close preview abillity when swipe back in preview view
=> [PB-2951]: bugfix/Swipe back from preview action leads to quitting folders

src/components/modals/AddModal/index.tsx, src/components/modals/BottomModal/index.tsx, src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx
-  Fixed bug that sometimes caused the modal to not display correctly and to be hidden at the bottom of the screen.
=> [PB-2965] bugfix/Graphical problems

__mocks__/@dr.pogodin/react-native-fs.ts, ios/Internxt.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, src/components/modals/AddModal/index.tsx, src/network/NetworkFacade.ts, src/network/crypto.ts, src/network/download.ts, src/services/FileSystemService.ts, src/services/NetworkService/download.ts, src/services/common/filesystem/fileCacheManager.spec.ts, src/services/common/logger/logger.service.ts, src/services/common/media/image.service.ts, src/services/drive/constants.ts, src/services/drive/events/driveEvents.ts, tsconfig.json, yarn.lock
- Changed `react-native-fs` to forked and mantained library `@dr.pogodin/react-native-fs`
- Added thumbnail creation for videos
=> [PB-2600] bugfix/Error uploading mobile app

android/app/build.gradle, android/app/src/main/res/values/strings.xml, ios/Internxt.xcodeproj/project.pbxproj, ios/Internxt/Info.plist, ios/Internxt/Supporting/Expo.plist, package.json, src/components/modals/AddModal/index.tsx, src/screens/drive/DrivePreviewScreen/DrivePreviewScreen.tsx, src/store/slices/drive/index.ts
- Update project version to new release
- Added logs to record possible errors when upload images or download files
=> [PB-3286,PB-3278] bugfix/Error using "Take a photo and upload" and app crashes download big files

android/app/build.gradle, assets/lang/strings.ts, ios/Internxt.xcodeproj/project.pbxproj, ios/Internxt/Info.plist, ios/Podfile.lock, package.json, src/components/AppTextInput/index.tsx, src/components/modals/DriveItemInfoModal/index.tsx, src/components/modals/DriveRenameModal/index.tsx, src/contexts/Drive/Drive.context.tsx, src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx, src/screens/drive/DrivePreviewScreen/DrivePreviewScreen.tsx, src/services/drive/constants.ts, src/services/drive/file/driveFile.service.ts, src/store/slices/drive/index.ts, yarn.lock
- Fixed iPhone 15 download error related to react-native-fs library
- Fixed Android cursor positioning when delete selected text in TextInput
=> [PB-3278,PB-2949,PB-2967] Bugfix/Testing issues

android/app/build.gradle, package.json, src/components/AppTextInput/index.tsx, src/components/CodeInput/index.tsx, src/screens/SignInScreen/index.tsx
- Fixed autodelete when typing on numeric keypad
=> [_] bugfix/Fix android numerical pad issue

src/network/NetworkFacade.ts, src/network/download.ts, src/services/drive/file/driveFile.service.ts
- Added download function in one part again for thumbnails
=> [PB-3582] bugfix/Thumbnails not showing

src/screens/SecurityScreen/index.tsx
- Password change option has been hidden
=> [_]: Feature/Hide password change

src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx, src/components/ui-kit/touchables/BackButton/BackButton.tsx
- Fixed overlap name of item in header with magnifyed glass
- Added more margin to button in order to separte it from bottom border of screen
=> [PB-3575] Bugfix/UI fixes

android/app/build.gradle, android/app/src/main/res/values/strings.xml, ios/Internxt/Info.plist, ios/Internxt/Supporting/Expo.plist, package.json, src/components/modals/RunOutOfStorageModal/index.tsx, src/helpers/utils.ts, src/screens/AccountScreen/index.tsx, src/screens/StorageScreen/index.tsx, src/services/drive/constants.ts
- Updated version and redirct to website when press buy or update plan buttons
=> [_] feature/Add redirection in plans buttons to web links

android/app/src/main/AndroidManifest.xml
- Disabled android app backup option
=> [PB-4532] feature/Disable android app backup

src/components/AppScreen/index.tsx, src/components/modals/BottomModal/index.tsx, src/components/modals/CenterModal/index.tsx, src/services/PaymentService.ts, src/store/slices/payments/index.ts
- Changed status bar colors for better visibility in android with white status bar icons
- Fixed load invoices and load subscription call with correct params
=> [PB-178] Feature/Fix status bar colors

src/App.tsx, src/screens/common/LockScreen/LockScreen.tsx, src/services/AsyncStorageService.ts, src/services/AuthService.ts, src/store/slices/app/index.ts, src/store/slices/auth/index.ts
- Updated cleanup logic to reset screen lock states when not enabled
- Refresh token when app goes foreground only when expiration date is less than 3 days
=> [PB-4521] bugfix/White screen after screen lock

src/components/SearchInput/SearchInput.tsx, src/components/modals/AddModal/index.tsx, src/components/modals/DriveItemInfoModal/index.tsx, src/network/upload.ts, src/screens/drive/DriveFolderScreen/DriveFolderEmpty.tsx, src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx
- Added silent retry when uploading a file (up to three attempts)
- Added some correct styles in dark mode
- Fixed focus folder bug (when creating a new folder, and navigating to it, the focus folder is still the parent)
=> [PB-4539] bugfix/Add silent upload retry

src/components/modals/AddModal/index.tsx, src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx, src/services/drive/file/utils/uploadFileUtils.ts
- File list not refresh after upload from gallery or take a photo, added a delay that gives enough time to update the list correctly
=> [PB-4557] bugfix/File list not refresh after upload

src/components/UserProfilePicture/index.tsx, src/screens/PlanScreen/index.tsx
Fixed bugs related with avatar display: 
- Account icon is misplaced: the avatar seems that was misplaced because the border only was displayed for left and top sided
- When remove the avatar image, not update correctly and appears empty instead show de username initials
=> [PB-4584,PB-4585] bugfix/Account avatar display

android/build.gradle
- Updated android target version to 35
=> [PB-4587] feature/Update android target version

android/app/build.gradle, assets/lang/strings.ts, src/hooks/useSecurity.ts, src/services/AsyncStorageService.ts, src/services/security/security.service.ts, src/types/index.ts
- The way in which security alerts are displayed has been modified.
- It can be disabled so that it does not show it again even after 24 hours.
- If a change in security is detected, the alert will be displayed again if there is any type of risk
=> [_]: Modified security alert handling

src/App.tsx, src/hooks/useSecurity.ts
- Excute security service always when app becomes "active"
=> [PB-4533]: feature/Security check always when app becomes active
