internxt/drive-mobile

package.json
src/services/photos/PhotosCameraRollService.ts
src/services/photos/PhotosLocalDatabaseService/index.ts
src/services/photos/PhotosLocalDatabaseService/tables/tmp_camera_roll.ts
src/services/photos/PhotosSyncService.ts
src/services/photos/index.ts
yarn.lock

This PR improves local indexing performance on the Photos Sync module.
Mainly: 
- (1) Replaces inserting photos one-by-one for bulk inserts on SQLite.
- Provides a temporal fix for a buggy behavior of [react-native-camera-roll](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/359) on Android when using cursors. (Kudos to @BohdanSol for the fork, great job!)
- Improves indexing time on iOS from several minutes to ~30 seconds due to (1) for 10,000 photos. (Tested on iPhone 11)
Advisable to double-check with detail @carlossalasamper 
Tested mainly local indexing with 10,000 photos for:
- iOS (iPhone 11): 30s 
- Android (Google Pixel 3): 8s

[TICK-278]: feat/improve-sync-performance

---

src/@inxt-js/services/api.ts
src/@inxt-js/services/request.ts
src/services/network/upload.ts

Uses an endpoint that double-checks the object existence in our storage before confirming the upload.

[_]: fix/ensure-create-entry-from-frame

---

ios/Internxt.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
src/network/NetworkFacade.ts
src/services/NetworkService/download.ts
yarn.lock

This PR adds support for native encrypt/decrypt operations for iOS
This functionality is provided by [@internxt/rn-crypto](https://github.com/internxt/rn-crypto)
The encrypt/decrypt is now made on a background thread using a Swift OperationQueue which doesn't block the UI and let us encrypt/decrypt multiple files at the same time without frozing the UI.
Notes:
- There's still an operation blocking the UI thread which is coming from @inxt-js/lib/crypto.ts, from a function called GenerateFileKey, this function uses JS crypto which is not too performant so it still blocks briefly the UI thread

[DRIV-85] Add native encrypt decrypt ios

---

src/navigation/RootNavigator.tsx
src/services/photos/PhotosCommonService.ts
src/store/slices/auth/index.ts

In Android devices, the isLoggedIn value was getting updated after we initialized the navigator, since the navigator loads an initialRoute once, if isLoggedIn is false, it redirects to the login screen

[FIX]: Is logged initialization failing due to JS too fast

---

src/network/NetworkFacade.ts
src/services/FileSystemService.ts

This PR provides a cleanup function that gets executed right after an upload operation finish, doesn't matter if the operation success or fails. 
We do the cleanup on fail since we don't know why the operation is failing, if the operation is failing due to an encryption problem and we keep picking the old file, the upload will keep failing.

[FEATURE]: Removed encrypted files after upload fail/success

---

app.config.ts
src/plugins/SentryPlugin.ts

Right now, each update (update => expo publish) being released, was compatible with whatever app version it hits, with this, we can restrict which app versions will be updated with each publish
Also, for vissibility, a release ID has been added so we can identify each update in Sentry correctly

[_]: Runtime version for updates & release ID

---

app.config.ts

Seems like Expo runtimeVersion doesn't works out of the box for Bare workflows, so I'm reverting it until we add it to the Manifest and Info.plist automatically

[_]: Revert runtimeVersion

---

README.md
android/gradle.properties
app.config.ts
ios/Internxt.xcodeproj/project.pbxproj
ios/Podfile.lock
ios/Podfile.properties.json
package.json
src/network/NetworkFacade.ts
src/services/FileSystemService.ts
yarn.lock

Adds hermes support for iOS and Android
Upgrades react-native-reanimated to latest version since we are not using Expo managed workflow
Hermes provides better memory usage specially for low end devices compared to JSI
https://reactnative.dev/docs/hermes

Add hermes JS engine

---

README.md
package.json
yarn.lock

Requirements added in README.md with JDK, SDK, NDK and CMake version. Also the version of react-native-reanimated has been changed to 2.9.1 and it has been fixed.

Adding Requirements in README.md and react-native-reanimated version changed and fixed.

---

src/components/modals/SortModal/index.tsx
src/screens/DriveScreen/index.tsx
src/services/drive/file/driveFile.service.ts
src/types/drive.ts
src/types/prettysize.d.ts

Some items were being sorted incorrectly in Drive.
What changed:
- The size being received was an string, so sorting by size was incorrect
- The name of the files has been converted to hex, so we can sort them in any language

[_]:(hotfix) Fix incorrect sorting for drive items

---

assets/lang/strings.ts
ios/Internxt.xcodeproj/project.pbxproj
src/App.tsx
src/components/AppButton/index.tsx
src/navigation/RootNavigator.tsx
src/navigation/TabExplorerNavigator.tsx
src/screens/DeactivatedAccountScreen/DeactivatedAccountScreen.tsx
src/screens/DeactivatedAccountScreen/index.ts
src/store/slices/auth/index.ts
src/store/slices/referrals/index.ts
src/styles/tailwind.css
src/styles/tailwind.json
src/types/index.ts
src/types/navigation.ts
tailwind.config.js

Mobile wasn't able to detect when an account has been successfully deleted/deactivated. This PR provides a mechanism to detect if the account has been deleted.
1- When the user press the "deactivate account button" we store a `isDeactivatingAccount` key in the async storage
2- If the user comes back to the app, and an API request throws a 401 and the key exists we assume the account has been deleted since the token is revoked, we then redirect the user to the new DeactivatedAccount screen

[MT-58]:(feature) Account deactivated success screen

---

src/components/DriveItemGrid/index.tsx
src/components/DriveItemSkinSkeleton/index.tsx
src/components/DriveList/index.tsx
src/components/modals/MoveItemsModal/index.tsx
src/screens/DriveScreen/index.tsx
src/screens/drive/SharedScreen/SharedScreen.tsx
src/services/common/time/time.service.ts
src/services/drive/constants.ts
src/services/drive/database/driveLocalDB.ts
src/services/drive/file/driveFile.service.ts
src/services/drive/index.ts
src/store/slices/app/index.ts
src/store/slices/auth/index.ts
src/store/slices/drive/index.ts
src/store/slices/ui/index.ts
src/styles/tailwind.css
src/styles/tailwind.json
src/types/drive.ts
src/types/index.ts
tailwind.config.js

Branch coming from `feature/add-photos-analytics`
- Added thumbnails for files that has them only in Drive grid mode. 
- Last Drive view mode now is persisted when you return to the app.
- Added grid mode skeletons

[MT-53]: (feature) see drive thumbnails

---

src/services/FileSystemService.ts

Some issues about this file missing on iOS has been found in Sentry, I believe the file contains some metadata about deleted stuff as stated here: https://discussions.apple.com/thread/252325852
Since the file is stored in the tmp dir, and we clean that dir on startup, we should prevent that file from being deleted. I think is the OS the one that is writing this file.

[_]:(hotfix) Avoid startup crash due to missing file

---

ios/Podfile.lock
src/components/drive/lists/items/DriveGridModeItem/DriveGridModeItem.tsx
src/components/drive/lists/items/DriveListModeItem/DriveListModeItem.tsx
src/components/modals/MoveItemsModal/index.tsx
src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx
src/hooks/useDriveItem.ts
src/screens/drive/DriveFolderScreen/DriveFolderScreen.tsx
src/screens/drive/RecentsScreen/RecentsScreen.tsx
src/screens/drive/SharedScreen/SharedScreen.tsx
src/services/drive/database/driveLocalDB.ts
src/services/drive/folder/driveFolder.service.ts
src/store/slices/drive/index.ts
src/types/drive.ts
src/useCases/drive/getShareLink.ts

Some files such .DS_Store or .env was being identified incorrectly as folders, the code flow should be improved for Drive in mobile since some interface mappings are not straightforward, but at least with this we can identify consistently a file and a folder

[_]:(fix) Identify files without extensions correctly

---

src/services/photos/database/photosLocalDB.ts
src/services/photos/database/tables/deviceSync.ts

Fixes a corner case where the same Photo can be inserted in the db twice, happens when:
1. We begin the sync process
2. We pull the photo from the server, but the photo in the device is already in the sync queue
3. The photo is already in the local db, but we check it agains the server since when we checked before against the local db, the Photo was not yet in the local DB
4. Photos server says the photo exists and gives us the Photo
5. We try to insert the Photo, but is alreay in the localDB causing a constraint violation in SQlite (not anymore with this PR)

[_]:(fix) Avoid photo name collision in the local db

---

package.json
src/components/modals/AddModal/index.tsx
yarn.lock

**The problem**
When a file is picked from the file explorer the given URI is encoded, other libraries such react-native-fs were encoding the already encoded path, so no file was being found.
**Solution**
Avoid encoding the already encoded paths to files, basically we provide a decoded path, each library handles it correctly later

[MT-108]:(fix) Encode/Decode paths correctly for file uploads

---

src/components/modals/AddModal/index.tsx
src/components/photos/VideoViewer/VideoViewer.tsx
src/network/NetworkFacade.ts
src/screens/PhotosPreviewScreen/index.tsx
src/screens/SignInScreen/index.tsx
src/screens/SignUpScreen/index.tsx
src/screens/drive/DrivePreviewScreen/DrivePreviewScreen.tsx
src/screens/drive/DrivePreviewScreen/DriveVideoPreview.tsx
src/services/FileSystemService.ts
src/services/photos/network/photosNetwork.service.ts
src/store/slices/drive/index.ts

Fix not playable videos for Drive previews.
In some cases the native video player is not able to reproduce the video, usually due to codec incompatibility. on iOS we use AVFoundation, on Android ExoPlayer.
**Solution**
We detect when we cannot load the video in the in app player, when that happens, and the user taps on the play button, we prompt the user the native OS video player

[MT-111]:(fix) Fix not playable video previews

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/Internxt/Info.plist
ios/Internxt/Supporting/Expo.plist
package.json

- Fix download file to device storage on Android 12+
- Encrypt private key correctly when modifying password

[_]: Bump version to 1.5.28

---

src/services/photos/sync/devicePhotosScanner/devicePhotosScanner.ts

This PR switches the cache key for storing the Photos items in the memory while retrieving them. Creation time key was used before, but in production some photos with null values there exists (still unknown why) making the previous key not reliable.

[_]:(fix) Make Photos cache key more reliable by using the ID

---

src/components/PhotosSyncStatusWidget/index.tsx
src/services/AuthService.ts
src/services/common/keys/index.ts
src/services/common/keys/keys.service.ts

This PR decrypts correctly the private key during login.
Due to not decoding the private key on mobile, the password modification was generating a new privateKey generated from the still encrypted privateKey instead of the plain one, now we decrypt the privateKey during login

[PB-754]:(fix) Decrypt private key during login

---

ios/Internxt.xcodeproj/project.pbxproj
src/App.tsx
src/contexts/Drive/Drive.context.tsx
src/contexts/Drive/helpers.ts
src/services/drive/file/driveFile.service.ts
src/services/drive/folder/driveFolder.service.ts
src/types/drive.ts
src/types/index.ts

**PROBLEM:**
When an item is modified on another platform (renamed or moved to the trash), the old item still appears (with the old name or in the folder from which the item was deleted).
**FIX:**
Now, we check if the item has been modified and is cached, and if so, we remove the item from the local DB to replace it with the new one.

[PB-570]: Fix/invalidate file cache correctly

---

src/screens/SignInScreen/index.tsx

- Display backend error message when login fails instead of generic message

[PB-2739]  bugfix/Unable to log in on some devices

---

android/app/build.gradle
ios/Internxt/Info.plist
src/network/NetworkFacade.ts

- Improved frequency of update of download progress on ios and download concurrency

[_] feature/Improved display of download progress on iOS and download concurrency

---

assets/lang/strings.ts
src/components/modals/AddModal/index.tsx
src/contexts/Drive/Drive.context.tsx
src/network/upload.ts
src/services/drive/database/driveLocalDB.ts
src/services/drive/file/driveFile.service.ts
src/services/drive/file/utils/checkDuplicatedFiles.ts
src/services/drive/file/utils/getUniqueFilename.ts
src/services/drive/file/utils/prepareFilesToUpload.ts
src/services/drive/file/utils/processDuplicateFiles.ts
src/services/drive/file/utils/uploadFileUtils.ts

- Added logic to handle if file already exists
- It solves the problem with the pagination, as it is possible that not all the files are uploaded, it makes a request to the server to check if the file already exists before uploading it, this way we avoid the error of trying to upload a heavy file that already exists and you get an error at the end after the wait.

[PB-3737] feature/Handling of Existing Files During Uploads

---

android/app/src/main/AndroidManifest.xml
ios/Internxt/Info.plist

**Reduce app permissions to follow principle of least privilege**
Removes unnecessary permissions identified in security audit SECURITUM-2414556-006:
**Android:**
- android.permission.RECORD_AUDIO
- android.permission.SYSTEM_ALERT_WINDOW
**iOS:**
- NSMicrophoneUsageDescription
These permissions were not essential for core app functionality and their removal improves user privacy and security posture

[PB-4534] feature/Remove unnecessary permissions

---

src/components/modals/MoveItemsModal/index.tsx
src/contexts/Drive/Drive.context.tsx
src/store/slices/drive/index.ts

**Bug:**
- UI not reflecting moved items in drive list correctly after move it 
**Fix applied:**
- Optimistic updates: Item move to folder and update UI and local state instantly
- Auto rollback: Reverts all changes if move item call to API fails

[PB-4557] bugfix/Items list not refresh correctly
